trigger: none
pool: HLD
variables:
  workdir: '$(System.DefaultWorkingDirectory)/HLD/dev/frountend'
stages:
  - stage: SetupInitialize
    displayName: Terraform Setup & Backend Initialization
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workdir)'
            backendServiceArm: 'HLD'
            backendAzureRmStorageAccountName: 'hld12345terraformpipe1'
            backendAzureRmContainerName: 'hld-container'
            backendAzureRmKey: 'dev.terraform.tfvars'
  - stage: SecurityScan
    displayName: Infrastructure Security Scanning
    dependsOn: SetupInitialize                     # we have supply stage name on which it is depends on
    jobs:
      - job: 
        displayName: TFSEC Scanning Wala Job
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.28.14'
            dir: '$(workDir)'
  - stage: plan
    displayName: "Terraform Plan - Test"
    dependsOn: SecurityScan
    jobs:
      - job: 
        displayName: terraforminit
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workdir)'
            backendServiceArm: 'HLD'
            backendAzureRmStorageAccountName: 'hld12345terraformpipe1'
            backendAzureRmContainerName: 'hld-container'
            backendAzureRmKey: 'dev.terraform.tfvars'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(workdir)'
            environmentServiceNameAzureRM: 'HLD'
      - job: 
        displayName: infracost
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'infracost breakdown --path=.'
            workingDirectory: '$(workdir)'
  - stage: Approval
    displayName: ManualApproval
    pool: server
    jobs:
      - job: 
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'singhchahalajmer@gmail.com'
            approvers: 'Ajmer'
            allowApproversToApproveTheirOwnRuns: false
            instructions: 'Test pipeline'
  - stage: apply
    displayName: terrafrom apply
    dependsOn: Approval
    jobs:
      - job: 
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(workdir)'
            environmentServiceNameAzureRM: 'HLD'