trigger: none
pool: HLD
variables:
  workdir: '$(System.DefaultWorkingDirectory)/HLD/dev/frountend'
stages:
  - stage: 
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workdir)'
            backendServiceArm: 'HLD'
            backendAzureRmStorageAccountName: 'hld12345terraformpipe1'
            backendAzureRmContainerName: 'hld-container'
            backendAzureRmKey: 'dev.terraform.tfvars'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(workdir)'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(workdir)'
            environmentServiceNameAzureRM: 'HLD'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'destroy'
            workingDirectory: '$(workdir)'
            commandOptions: '--auto-approve'
            environmentServiceNameAzureRM: 'HLD'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'output'
            workingDirectory: '$(workdir)'
            environmentServiceNameAzureRM: 'HLD'