trigger: none
pool: HLD
variables:
  workdir: '$(System.DefaultWorkingDirectory)/HLD/dev/frountend'
stages:
  - stage: install
    displayName: terrafrom install
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
  - stage: init
    displayName: terrafrom init
    dependsOn: install
    jobs:
      - job: 
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workdir)'
            backendServiceArm: 'HLD'
            backendAzureRmStorageAccountName: 'hld12345terraformpipe1'
            backendAzureRmContainerName: 'hld-container'
            backendAzureRmKey: 'dev.terraform.tfvars'
  - stage: TFScanning 
    displayName: tfscan
    dependsOn: init
    jobs:
      - job: 
        displayName: TFSEC Scanning Wala Job
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.28.14'
            dir: '$(workDir)'
  - stage: plan
    displayName: terrafrom plan
    dependsOn: TFScanning
    jobs:
      - job: 
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(workdir)'
            environmentServiceNameAzureRM: 'HLD'
  - stage: apply
    displayName: terrafrom apply
    dependsOn: plan
    jobs:
      - job: 
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(workdir)'
            environmentServiceNameAzureRM: 'HLD'